#!/usr/bin/perl

use strict;
use warnings;
use WWW::Mechanize;
use YAML qw/LoadFile/;

my $mech = WWW::Mechanize->new();
my $config = LoadFile("config.yml");

$mech->get("http://www.myfitnesspal.com/account/login");
$mech->submit_form(
    fields => {
        username => $config->{username},
        password => $config->{password},
    }
);
print $mech->content;        
