#!/usr/bin/perl

use strict;
use warnings;
use WWW::Mechanize;
use YAML qw/LoadFile/;
use XML::XPath;

my $mech = WWW::Mechanize->new();
my $config = LoadFile("config.yml");

$mech->get("http://www.myfitnesspal.com/account/login");
$mech->submit_form(
    fields => {
        username => $config->{username},
        password => $config->{password},
    }
);
$mech->get("http://www.myfitnesspal.com/reports/results/nutrition/Net%20Calories/30");
my $xp = XML::XPath->new(xml => $mech->content);
my $nodeset = $xp->find('//chart_data/row/number/text()');
for my $i (1..$nodeset->size) {
    print $nodeset->get_node($i)->getValue()."\n";
}
